export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  larkAppId: process.env.LARK_APP_ID ?? "",
  larkAppSecret: process.env.LARK_APP_SECRET ?? "",
  larkRedirectUri: process.env.LARK_REDIRECT_URI ?? "",
  larkAdminUserIds: process.env.LARK_ADMIN_USER_IDS ?? "",
  larkDailyInsightChatId: process.env.LARK_DAILY_INSIGHT_CHAT_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
};
