import { beforeEach, describe, expect, it, vi } from "vitest";

const { storagePutMock } = vi.hoisted(() => ({
  storagePutMock: vi.fn(),
}));

vi.mock("server/storage", () => ({
  storagePut: storagePutMock,
}));

vi.mock("./_core/env", () => ({
  ENV: {
    forgeApiUrl: "https://forge.test/api/",
    forgeApiKey: "forge-test-key",
  },
}));

import { generateImage } from "./_core/imageGeneration";

describe("image generation service", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    storagePutMock.mockReset();
  });

  it("uses the Forge service credential, stores the generated bytes, and returns the storage URL", async () => {
    const imageBytes = Buffer.from("generated png bytes");
    const fetchMock = vi.spyOn(globalThis, "fetch").mockResolvedValue(
      new Response(
        JSON.stringify({
          image: {
            b64Json: imageBytes.toString("base64"),
            mimeType: "image/png",
          },
        }),
        { status: 200, headers: { "content-type": "application/json" } },
      ),
    );
    storagePutMock.mockResolvedValue({
      key: "generated/test.png",
      url: "/api/storage/generated/test.png",
    });

    const result = await generateImage({ prompt: "改善事例を画像化" });

    expect(result).toEqual({ url: "/api/storage/generated/test.png" });
    expect(fetchMock).toHaveBeenCalledTimes(1);
    const [requestUrl, requestInit] = fetchMock.mock.calls[0];
    expect(requestUrl).toBe("https://forge.test/api/images.v1.ImageService/GenerateImage");
    expect(requestInit?.headers).toMatchObject({
      authorization: "Bearer forge-test-key",
      "content-type": "application/json",
    });
    expect(String((requestInit?.headers as Record<string, string>).authorization)).not.toContain("lark");
    expect(storagePutMock).toHaveBeenCalledWith(
      expect.stringMatching(/^generated\/\d+\.png$/),
      imageBytes,
      "image/png",
    );
  });

  it("does not write to storage and reports the upstream response when generation fails", async () => {
    vi.spyOn(globalThis, "fetch").mockResolvedValue(
      new Response("temporary upstream failure", {
        status: 503,
        statusText: "Service Unavailable",
      }),
    );

    await expect(generateImage({ prompt: "失敗ケース" })).rejects.toThrow(
      "Image generation request failed (503 Service Unavailable): temporary upstream failure",
    );
    expect(storagePutMock).not.toHaveBeenCalled();
  });
});
